# Generated by Django 4.1.7 on 2023-02-27 06:21

from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.ImageField(upload_to=feed.models.get_image_filename),
        ),
    ]
